from __future__ import annotations

CURATED_AUTHORITY_TREE = [
    {
        "id": "formation",
        "label_en": "Formation",
        "label_zh": "形成",
        "summary_en": 'Contract coming into existence: agreement, consideration, intention, capacity, and formality.',
        "summary_zh": "合同从无到有的阶段：协议、约因、法律约束意图、行为能力与形式要求。",
        "subgrounds": [
            {
                "id": "agreement",
                "label_en": "Agreement",
                "label_zh": "协议",
                "summary_en": "Objective consensus, including offer, acceptance, and certainty.",
                "summary_zh": "客观合意，包括要约、接受与协议确定性。",
                "topic_labels": [
                    "Agreement (Offer and Acceptance)",
                    "Offer vs. Invitation to Treat",
                    "Communication of Acceptance",
                ],
                "children": [
                    {"en": "Offer vs. invitation to treat", "zh": "要约与邀请要约的区分"},
                    {"en": "Rules of acceptance", "zh": "接受的规则"},
                    {"en": "Certainty of agreement", "zh": "协议确定性"},
                ],
            },
            {
                "id": "consideration",
                "label_en": "Consideration",
                "label_zh": "约因",
                "summary_en": "Exchange of value and the enforceability of variations.",
                "summary_zh": "价值交换与合同变更可执行性。",
                "topic_labels": ["Consideration"],
                "children": [],
            },
            {
                "id": "intention",
                "label_en": "Intention to Create Legal Relations",
                "label_zh": "法律约束意图",
                "summary_en": "Whether the parties objectively intended legal enforceability.",
                "summary_zh": "当事人是否客观上意图产生法律约束力。",
                "topic_labels": ["Intention to Create Legal Relations"],
                "children": [],
            },
            {
                "id": "capacity",
                "label_en": "Capacity",
                "label_zh": "行为能力",
                "summary_en": "Who may contract and on what terms.",
                "summary_zh": "谁有能力订立合同，以及能力限制如何影响效力。",
                "topic_labels": ["Capacity"],
                "children": [],
            },
            {
                "id": "formality",
                "label_en": "Formality",
                "label_zh": "形式要求",
                "summary_en": "Writing, signature, and formal validity requirements.",
                "summary_zh": "书面、签署与形式有效性要求。",
                "topic_labels": ["Formality"],
                "children": [],
            },
        ],
    },
    {
        "id": "contents",
        "label_en": "Contents",
        "label_zh": "内容",
        "summary_en": "What the contract says, how its terms are identified, interpreted, implied, classified, and controlled.",
        "summary_zh": "合同内容为何：条款如何识别、解释、默示、分类与控制。",
        "subgrounds": [
            {
                "id": "term_identification",
                "label_en": "Term Identification",
                "label_zh": "条款识别",
                "summary_en": "Express terms, representations, and the parol evidence rule.",
                "summary_zh": "明示条款、陈述与口头证据规则。",
                "topic_labels": ["Express Terms and the Parol Evidence Rule"],
                "children": [
                    {"en": "Express terms vs representations", "zh": "明示条款与陈述的区分"},
                    {"en": "Parol evidence rule", "zh": "口头证据规则"},
                ],
            },
            {
                "id": "interpretation",
                "label_en": "Interpretation",
                "label_zh": "条款解释",
                "summary_en": "Objective interpretation and the context-versus-text lineage.",
                "summary_zh": "客观解释原则，以及文本与语境之间的权威发展路径。",
                "topic_labels": ["Express Terms and the Parol Evidence Rule"],
                "lineage_ids": ["interpretation_context_text"],
                "children": [
                    {"en": "Objective interpretation", "zh": "客观解释原则"},
                    {"en": "ICS / Sinoearn / Arnold / Wood line", "zh": "ICS / Sinoearn / Arnold / Wood 发展脉络"},
                ],
            },
            {
                "id": "implied_terms",
                "label_en": "Implied Terms",
                "label_zh": "默示条款",
                "summary_en": "Terms implied in fact, in law, by statute, or by custom.",
                "summary_zh": "事实默示、法律默示、成文法默示与惯例默示。",
                "topic_labels": ["Implied Terms", "Statutory Implied Terms"],
                "children": [
                    {"en": "Implied in fact", "zh": "事实默示"},
                    {"en": "Implied in law", "zh": "法律默示"},
                    {"en": "Implied by statute", "zh": "成文法默示"},
                    {"en": "Implied by custom", "zh": "惯例默示"},
                ],
            },
            {
                "id": "classification",
                "label_en": "Term Classification",
                "label_zh": "条款分类",
                "summary_en": "Condition, warranty, and innominate term analysis.",
                "summary_zh": "条件、保证与中间条款分析。",
                "topic_labels": [
                    "Classification of Terms",
                    "Conditions",
                    "Warranties",
                    "Innominate (Intermediate) Terms",
                ],
                "lineage_ids": ["intermediate_terms_hongkong_fir"],
                "children": [
                    {"en": "Conditions", "zh": "条件"},
                    {"en": "Warranties", "zh": "保证"},
                    {"en": "Innominate terms", "zh": "中间条款"},
                ],
            },
            {
                "id": "exemption_clauses",
                "label_en": "Exemption Clauses",
                "label_zh": "免责条款",
                "summary_en": "Construction, contra proferentem, and statutory control.",
                "summary_zh": "解释原则、不利起草者解释规则与成文法控制。",
                "topic_labels": ["Exemption Clauses", "Statutory Control of Exemption Clauses"],
                "children": [
                    {"en": "Common law construction", "zh": "普通法解释原则"},
                    {"en": "Statutory control", "zh": "成文法控制"},
                ],
            },
        ],
    },
    {
        "id": "vitiating_factors",
        "label_en": "Vitiating Factors",
        "label_zh": "效力瑕疵",
        "summary_en": "Reasons why an apparent contract may be void, voidable, or unenforceable.",
        "summary_zh": "为何表面成立的合同可能无效、可撤销或不可执行。",
        "subgrounds": [
            {
                "id": "misrepresentation",
                "label_en": "Misrepresentation",
                "label_zh": "失实陈述",
                "summary_en": "False statements inducing entry into contract.",
                "summary_zh": "引致订约的虚假陈述。",
                "topic_labels": ["Misrepresentation"],
                "children": [],
            },
            {
                "id": "mistake",
                "label_en": "Mistake",
                "label_zh": "错误",
                "summary_en": "Common, mutual, and unilateral mistake.",
                "summary_zh": "共同错误、相互错误与单方错误。",
                "topic_labels": ["Mistake"],
                "children": [],
            },
            {
                "id": "duress",
                "label_en": "Duress",
                "label_zh": "胁迫",
                "summary_en": "Physical and economic pressure undermining consent.",
                "summary_zh": "人身或经济压力导致同意受损。",
                "topic_labels": ["Duress"],
                "children": [],
            },
            {
                "id": "undue_influence",
                "label_en": "Undue Influence",
                "label_zh": "不当影响",
                "summary_en": "Improper influence and the Etridge adoption line.",
                "summary_zh": "不当影响与 Etridge 在香港的采纳路径。",
                "topic_labels": ["Undue Influence"],
                "lineage_ids": ["undue_influence_etridge"],
                "children": [],
            },
            {
                "id": "unconscionability",
                "label_en": "Unconscionability",
                "label_zh": "不合情理",
                "summary_en": "Common law and statutory unfairness control.",
                "summary_zh": "普通法与成文法下的不公控制。",
                "topic_labels": ["Unconscionability"],
                "lineage_ids": ["unconscionability_statutory"],
                "children": [],
            },
            {
                "id": "illegality",
                "label_en": "Illegality",
                "label_zh": "非法性",
                "summary_en": "Illegality in formation or performance.",
                "summary_zh": "订立时非法或履行时非法。",
                "topic_labels": ["Illegality"],
                "children": [],
            },
        ],
    },
    {
        "id": "termination",
        "label_en": "Termination",
        "label_zh": "终止",
        "summary_en": "When and how contractual obligations come to an end.",
        "summary_zh": "合同义务何时以及如何终止。",
        "subgrounds": [
            {
                "id": "performance",
                "label_en": "Performance",
                "label_zh": "履行完毕",
                "summary_en": "Discharge by full or sufficient performance.",
                "summary_zh": "因完全或充分履行而解除。",
                "topic_labels": ["By Performance"],
                "children": [],
            },
            {
                "id": "agreement_termination",
                "label_en": "Termination by Agreement",
                "label_zh": "协议终止",
                "summary_en": "Current graph placeholder. Refine with HKLII if distinct rescission or mutual discharge authorities are needed.",
                "summary_zh": "当前图谱中的占位结构；如需明确解除或双方同意终止的香港权威，可由 HKLII 补强。",
                "topic_labels": [],
                "children": [],
            },
            {
                "id": "repudiatory_breach",
                "label_en": "Repudiatory Breach",
                "label_zh": "违约终止",
                "summary_en": "Termination for serious breach or renunciation.",
                "summary_zh": "因根本违约或毁约表态而终止。",
                "topic_labels": ["By Breach"],
                "children": [],
            },
            {
                "id": "frustration",
                "label_en": "Frustration",
                "label_zh": "合同受挫",
                "summary_en": "Supervening events preventing or radically transforming performance.",
                "summary_zh": "后发事件阻止履行或使履行发生根本变化。",
                "topic_labels": ["By Frustration"],
                "children": [],
            },
        ],
    },
    {
        "id": "remedies",
        "label_en": "Remedies",
        "label_zh": "救济",
        "summary_en": "Consequences of breach and the available legal or equitable responses.",
        "summary_zh": "违约后的后果，以及普通法与衡平法下可获得的救济。",
        "subgrounds": [
            {
                "id": "damages",
                "label_en": "Damages",
                "label_zh": "损害赔偿",
                "summary_en": "Expectation, reliance, remoteness, and liquidated damages versus penalties.",
                "summary_zh": "预期利益、信赖利益、可预见性，以及约定赔偿金与罚金。",
                "topic_labels": [
                    "Unliquidated Damages",
                    "Remoteness of Damage",
                    "Liquidated Damages vs. Penalties",
                ],
                "lineage_ids": ["penalty_clauses_modern_test"],
                "children": [
                    {"en": "Expectation vs reliance", "zh": "预期利益与信赖利益"},
                    {"en": "Hadley v Baxendale remoteness", "zh": "Hadley v Baxendale 可预见性规则"},
                    {"en": "Liquidated damages vs penalties", "zh": "约定赔偿金与罚金"},
                ],
            },
            {
                "id": "equitable_remedies",
                "label_en": "Equitable Remedies",
                "label_zh": "衡平法救济",
                "summary_en": "Specific performance and injunctions.",
                "summary_zh": "强制履行与禁制令。",
                "topic_labels": ["Equitable Remedies"],
                "children": [
                    {"en": "Specific performance", "zh": "强制履行"},
                    {"en": "Injunctions", "zh": "禁制令"},
                ],
            },
        ],
    },
    {
        "id": "privity",
        "label_en": "Privity",
        "label_zh": "相对性",
        "summary_en": "Who may sue or rely on contractual rights.",
        "summary_zh": "谁可以主张合同权利或依赖合同利益。",
        "subgrounds": [
            {
                "id": "common_law_privity",
                "label_en": "Common Law Principle",
                "label_zh": "普通法原则",
                "summary_en": "Current graph placeholder for the privity baseline; refine with primary authorities.",
                "summary_zh": "当前图谱中的相对性基线占位节点；可由主要判例进一步补强。",
                "topic_labels": [],
                "children": [],
            },
            {
                "id": "statutory_exceptions",
                "label_en": "Statutory Exceptions",
                "label_zh": "成文法例外",
                "summary_en": "Contracts (Rights of Third Parties) Ordinance and related exceptions.",
                "summary_zh": "《合约（第三者权利）条例》及相关例外。",
                "topic_labels": ["Statutory Exceptions"],
                "children": [
                    {"en": "Cap. 623", "zh": "第 623 章"},
                ],
            },
        ],
    },
    {
        "id": "special_contracts",
        "label_en": "Special Contracts",
        "label_zh": "特殊合同类型",
        "summary_en": "Contract doctrine applied in recurrent subject-matter areas.",
        "summary_zh": "合同法在反复出现的特定交易领域中的适用。",
        "subgrounds": [
            {
                "id": "sale_of_goods",
                "label_en": "Sale of Goods",
                "label_zh": "货物买卖",
                "summary_en": "Sale of goods, transfer of title, and statutory implied terms.",
                "summary_zh": "货物买卖、所有权转移与成文法默示条款。",
                "topic_labels": ["Sale of Goods and Services"],
                "children": [],
            },
            {
                "id": "supply_of_services",
                "label_en": "Supply of Services",
                "label_zh": "服务提供",
                "summary_en": "Reasonable skill, care, time, and charges in service contracts.",
                "summary_zh": "服务合同中的合理技能、谨慎、时间与收费。",
                "topic_labels": ["Sale of Goods and Services"],
                "children": [],
            },
            {
                "id": "sale_of_land",
                "label_en": "Sale of Land",
                "label_zh": "土地买卖",
                "summary_en": "Land sale formalities and interim sale agreements.",
                "summary_zh": "土地交易的形式要求与临时买卖协议。",
                "topic_labels": ["Sale of Land and Leases"],
                "children": [],
            },
            {
                "id": "employment",
                "label_en": "Employment Contracts",
                "label_zh": "雇佣合同",
                "summary_en": "Service contracts, worker status, and relational obligations.",
                "summary_zh": "服务合同、劳动者身份与关系性义务。",
                "topic_labels": ["Employment Contracts"],
                "children": [],
            },
            {
                "id": "construction",
                "label_en": "Construction Contracts",
                "label_zh": "建设工程合同",
                "summary_en": "Standard forms, certification, and contractual variation in construction.",
                "summary_zh": "标准格式、认证与建设工程中的合同变更。",
                "topic_labels": ["Construction Contracts"],
                "children": [],
            },
            {
                "id": "credit_security",
                "label_en": "Credit, Security, and Guarantees",
                "label_zh": "信贷与担保",
                "summary_en": "Security devices, guarantees, and finance-related obligations.",
                "summary_zh": "担保工具、保证与融资合同义务。",
                "topic_labels": ["Credit, Security, and Guarantees"],
                "children": [],
            },
            {
                "id": "insurance",
                "label_en": "Insurance Contracts",
                "label_zh": "保险合同",
                "summary_en": "Utmost good faith and insurable interest issues.",
                "summary_zh": "最高诚信义务与可保利益问题。",
                "topic_labels": ["Insurance Contracts"],
                "children": [],
            },
        ],
    },
    {
        "id": "cross_cutting",
        "label_en": "Cross-Cutting Issues",
        "label_zh": "跨界议题",
        "summary_en": "Technology, cross-border, and procedure-focused overlays on contract doctrine.",
        "summary_zh": "技术、跨境与程序性议题对合同法的横向覆盖。",
        "subgrounds": [
            {
                "id": "electronic_contracting",
                "label_en": "Electronic Contracting and Emerging Technology",
                "label_zh": "电子合同与新兴技术",
                "summary_en": "Clickwrap, browsewrap, smart contracts, and privacy-related contract issues.",
                "summary_zh": "点击协议、浏览协议、智能合约与数据隐私相关合同问题。",
                "topic_labels": ["Electronic Contracting", "Smart Contracts & Blockchain", "Data Privacy in Contracts"],
                "children": [],
            },
            {
                "id": "cross_border_contracts",
                "label_en": "Cross-Border Contracts",
                "label_zh": "跨境合同",
                "summary_en": "Choice of law, jurisdiction, and foreign illegality treatment.",
                "summary_zh": "法律选择、管辖权与外国法下非法性的处理。",
                "topic_labels": ["Choice of Law", "Long-Arm Jurisdiction", "Foreign Illegality"],
                "children": [],
            },
            {
                "id": "dispute_resolution",
                "label_en": "Dispute Resolution",
                "label_zh": "争议解决",
                "summary_en": "Arbitration and mediation as contract-related dispute mechanisms.",
                "summary_zh": "以仲裁与调解处理合同争议。",
                "topic_labels": ["Arbitration", "Mediation"],
                "children": [],
            },
        ],
    },
]
